### ISSUE TITLE
Static directory not removed at uninstall

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/akkoma_ynh#16]
If you uninstall Akkoma, the static directory (`/home/yunohost.app/akkoma/static/`) is not removed or archived by the uninstall script of YNH... 

This can be a problem in case of later installation of a _new or clean instance_ of Akkoma for a new project for example.

The good idea can be to make a _backup_ somewhere, as the `static/` directory contain all the _custom_ assets and files of the removed instance.

**Comment by bugsysop** [comment]
Read this on Forgejo YNH package [README](https://github.com/YunoHost-Apps/forgejo_ynh):

>Due of the backup core only feature the data directory in /home/yunohost.app/forgejo is not removed. It must be manually deleted to purge user data from the app.

The solution is probably to _inform the user_ with a CLI example to backup & remove the directory if necessary.

**Comment by lapineige** [comment]
That's an interesting way to do it !
We should also warn during backup I think (the backup core only option is too transparent).

**Comment by bugsysop** [comment]
We can add this information somwhere:

>If someone want to delete the folder /home/yunohost.app/pleroma/ during removal of pleroma_ynh, it should add the --purge option. like all apps keeping datas in /home/yunohost.app/

https://github.com/YunoHost-Apps/pleroma_ynh/issues/233
