### ISSUE TITLE
How do we manage non-named/fixed version names ?

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/akkoma_ynh#2]
Contrary to Pleroma, Akkoma seems not to provide an URL with a dedicated version number/commit.
This means the version provided behind the URL will change after each (stable) release.

This is a trouble for Yunohost app packaging.
How do we manage it ?

Right now this means the sha2565sum will fails, and (hopefully) the installation process will stop instead of installing a newer version that might require manual intervention.
Hence, until we upgrade the package, installs will no longer be possible.

**Comment by Tagadda** [comment]
You could download a specific commit with a URL like this : https://akkoma.dev/AkkomaGang/akkoma/archive/4a78c431cfe1373ba09a3c02bc56502063975890.tar.gz (where `4a78c431cfe1373ba09a3c02bc56502063975890` is the commit sha)

**Comment by Tagadda** [comment]
You could try to adapt the glitch-soc auto updater

**Comment by Tagadda** [comment]
Also, for glitchsoc_ynh version number, I use the date of the last commit (eg. 2022.12.20~ynh1), to avoid 3.5.0~ynhinfinity ^^

**Comment by bugsysop** [comment]
@lapineige 
How this is managed actualy?

**Comment by lapineige** [comment]
It is not.
I'm getting the latest version, when it will change, install will break because of wrong sha256sum.

Thanks @Tagadda for the suggestion, I may go for this option.
