### ISSUE TITLE
Upgrade to new stable version

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/akkoma_ynh#20]
Maybe can we begin to test an upgrade to the new stable version of Akkoma 
https://meta.akkoma.dev/t/akkoma-stable-2023-02-lies-verifies-and-statistics/356

**Comment by bugsysop** [comment]
Still no release, but a git [branche](https://akkoma.dev/AkkomaGang/akkoma/src/branch/stable)

**Comment by lapineige** [comment]
And the sha256sum of the current release changed #19. Maybe some release candidate was released ? :thinking:

**Comment by lapineige** [comment]
I checked, it's a new OTP release that contains v3.6.0.
