### ISSUE TITLE
[Testing] Wrong path in config

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/akkoma_ynh#23]
In **Admin FE** these tow config parameters are wrong:

Path to **Upload** directory  
![akk-conf-bug-1-2023-02-14-AdminFE](https://user-images.githubusercontent.com/365281/218991909-e7d74f54-ef32-40bb-8121-ae10c1b72739.png)

Path to **Modules**  
![akk-conf-bug-2-2023-02-14-AdminFE](https://user-images.githubusercontent.com/365281/218991922-58999c7b-d875-4dae-8f18-2ff39b5d38b3.png)

`/var/lib/akkoma/` must be replaced with `/home/yunohost.app/akkoma/`

**Comment by lapineige** [comment]
Thank you for catching these !

**Comment by bugsysop** [comment]
I think the problem with **upload directory** is somewhere in the `config.exs` file generated at YNH install of Akkoma

From `/var/akkoma/config.exs`

```
config : pleroma, :instance, static_dir: "/home/yunohost.app/akkoma/static"
config : pleroma, Pleroma.Uploaders.Local, uploads: "/home/yunohost.app/akkoma/uploads"
```

Sorry I have no time to search more now...

**Comment by lapineige** [comment]
You mean it's already properly configured in that file but it's not the value shown in the admin UI ?
Then we are in bigger trouble that I thought...

**Comment by bugsysop** [comment]
`uploads` is proprely configured… But not the `modules` path...
I realy don't understand where is the problem with `uploads`.

In my Pleroma install (production, upgraded to last version) the `uploads` path is correct, but not the module one because is not set in `config.exs`

**Comment by lapineige** [comment]
If you change them (both settings) from the web admin, what happens in the config.exs file ?

By the way do you know what is the use of that module folder ?
For upload, I understood it's for media attachements.

**Comment by bugsysop** [comment]
No synchronisation from DB in `config.exs`
Note: it's why in case of upgrade you loose some customizations done in Admin FE

For the _modules_ if I remember well there are not used in OTP release if you don't make your own buil of Pleroma/Akkoma

**Comment by lapineige** [comment]
> Note: it's why in case of upgrade you loose some customizations done in Admin FE

Can we fix this ?

> For the modules if I remember well there are not used in OTP release if you don't make your own buil of Pleroma/Akkoma

Oh ok, so we don't care ?

**Comment by lapineige** [comment]
I can test a change in admin UI, as it is buggy since upgrade to 3.6.0 (same as https://github.com/YunoHost-Apps/akkoma_ynh/pull/21#issuecomment-1430338255).

I have the proper uploads folder settings in the config file too.

**Comment by joeldebruijn** [comment]
Same here, sinds upgrading tot 3.6.0, the Pleroma Admin front-end didnt show anything. 
After logging out, rebooting server and restarting Akkoma service, I still cant login:
![20230219-080911-Admin FE](https://user-images.githubusercontent.com/3906940/219934519-409edf22-6606-4b04-bee0-7d40b7f7a5d3.png)

Not sure its the same issue, but looked something similar so posted as a reply instead as separate issue.
The 3 Akkoma accounts on the server are happy tooting tho and still works.

**Comment by lapineige** [comment]
I can't login with the Log in button too, it only works with PleromaFE. Not sure it was the case before.

**Comment by joeldebruijn** [comment]
In my case via PleromaFE I still get errors:
![image](https://user-images.githubusercontent.com/3906940/219952446-f600dc6f-3ed0-4173-b130-756d9a8045a1.png)

**Comment by lapineige** [comment]
Yes, same for me. I don't understand where they are coming from.

**Comment by lapineige** [comment]
People with admin UI issues like this 404 : this is because the frontend is not up-to-date.

Starting with #28, it will be upgraded during each upgrade.
You could try it now, wait for it, or fix it right now with : `cd /var/www/akkoma/live && sudo -u akkoma bin/pleroma_ctl frontend install admin-fe --ref stable`.

**Comment by lapineige** [comment]
@bugsysop the original bug you mentioned is fixed in my instance manually in my instance, from the Admin FE.
I don't think we can fix that during upgrades. At least I don't know how to change those parameters from the command line.

For now on, I added the correct configuration in #28, for install only, thanks to one Akkoma maintainer help.

Thanks a lot for your help.
