### ISSUE TITLE
Javascript Execution Vulnerability

### ISSUE THREAD

**Issue by twizzay-code** [YunoHost-Apps/akkoma_ynh#29]
[This vulnerability was discovered today.](https://poa.st/notice/AW21NSFdXhFPb2Zzai)

![05-25-2023_09:59%:29PM](https://github.com/YunoHost-Apps/akkoma_ynh/assets/88040412/98977adf-1605-491c-aeea-1dddfc5ea05b)

**Comment by lapineige** [comment]
Thanks !
I don't know how to fix this, if anyone can help on this :pray:

**Comment by lapineige** [comment]
Fixed by #31

**Comment by lapineige** [comment]
That's the patch from yesterday included in 3.9.3 ? (#34) Or is it a new one ?

**Comment by lapineige** [comment]
It was merged. It should show up quickly.
If you want to upgrade faster : `yunohost app upgrade akkoma -u https://github.com/YunoHost-Apps/akkoma_ynh`
