### ISSUE TITLE
V3.9.3 patch not allowing media to be viewable

### ISSUE THREAD

**Issue by twizzayy** [YunoHost-Apps/akkoma_ynh#35]
After upgrading to v3.9.3 everything located at 'sub.domain.tld/media' is returning a 404 error. 

I tested removing different lines from the nginx config for my instance and restarting the nginx service.

The issue seems to be directly tied to the new 'location ~ ^/media' in the nginx config. 

Media always returned a 404 as long as this location matched regardless of what was in the body of the block. Even if it was empty.

Removing the location block entirely made media viewable. But this nullifies the CSP rules for the patch which is obviously not ideal.

**Comment by lapineige** [comment]
I don't know how to fix this 🤔

**Comment by lapineige** [comment]
Please check the latest PR :)
