### ISSUE TITLE
Update 3.9.3-yn3 not available

### ISSUE THREAD

**Issue by novakeith** [YunoHost-Apps/akkoma_ynh#38]
Says akkoma package is broken 
<img width="374" alt="Screenshot 2023-06-02 at 8 46 47 PM" src="https://github.com/YunoHost-Apps/akkoma_ynh/assets/11334820/d7ca01d1-1bfe-4524-ba76-6662f54e3a1e">

I am on [YunoHost](https://yunohost.org/) 11.1.20 (stable).

**Comment by lapineige** [comment]
I don't know why it says that, that is likely to be an error.
